name: his_words
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.6

  # state management
  bloc: ^8.1.4

  # manager
  get_it: ^7.7.0

  # Internationalisation
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # utils
  provider: ^6.1.2
  path_provider: ^2.1.4
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  mutex: ^3.1.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
